spring:
  application:
    name: Simwor
  datasource:
    url: jdbc:mysql://121.37.207.241:33060/simwor
    username: rayslee
    password: abcd1234..
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888